### ISSUE TITLE
Remove Candidate ID from Vote

### ISSUE THREAD

**Issue by kristian2680** [Vict2976/Liquid-Democracy#15]
Lars og jeg snakkede om der er et CandidateID i Vote, og det skal vel fjernes

**Comment by Vict2976** [comment]
<img width="779" alt="Screenshot 2023-03-01 at 15 28 15" src="https://user-images.githubusercontent.com/71268129/222169114-2f2c0edc-bbff-48f3-8756-98def8675872.png">

**Comment by Vict2976** [comment]
Det har jeg ikke

**Comment by kristian2680** [comment]
<img width="1167" alt="Skærmbillede 2023-03-01 kl  15 31 33" src="https://user-images.githubusercontent.com/90180990/222170283-dc4f21a2-e781-4a4f-b5e1-d606cb5f8c38.png">



Nej same, men den skal vel væk som parameter her ik?

**Comment by Vict2976** [comment]
Ahh ja helt klart, den skal fjernes :)

**Comment by Vict2976** [comment]
Lasse did the fix
